### ISSUE TITLE
Chapter 16: chapter opening

### ISSUE THREAD

**Issue by leigh-data** [feldroy/django-crash-course#221] opened 2020-03-29 15:27 UTC
## Chapter 16 Opening

>The first tool we install into our projects is Cookiecutter, which we’ll be using in future extensions and books. {Sample}

The {Sample} part is is unexplained.

**Comment by quique** [comment] 2020-03-29 20:01
Duplicate of #211

**Closed** 2020-06-22 22:12 UTC
