### ISSUE TITLE
Import error for 'assertContains'

### ISSUE THREAD

**Issue by goutomroy** [feldroy/django-crash-course#307] opened 2020-07-15 04:02 UTC
I am getting import error `Cannot find reference 'assertContains' in 'asserts.py' ` for importing
`from pytest_django.asserts import assertContains`  in `chapter 52.3` of book version `beta-20200713`. What can be the problem?

Thanks in advance.

**Comment by pydanny** [comment] 2020-07-20 21:20
I can't reproduce this error. Do you have your environment active with all your requirements installed?

**Comment by goutomroy** [comment] 2020-07-22 07:49
Yes, mu environment is acive and I get no other import error except this one and I did **pip install -r requirements/local.txt** correctly.

**Comment by pydanny** [comment] 2020-07-29 22:21
No one else is reporting this error. Closing this for now, we'll reopen if someone else can duplicate your error.

**Closed by pydanny** 2020-07-29 22:21 UTC
